version: '1.0.{build}'
image: Visual Studio 2017

branches:
  only:
  - master

environment:
  matrix:
    - configuration: Debug
    - configuration: Release

init:
  - cmd: git config --global core.autocrlf true

build_script:
  - cmd: dotnet build /p:Configuration=%configuration% /p:TreatWarningsAsErrors=True

test_script:
  - cmd: dotnet test /p:Configuration=%configuration%
